-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.clean_data
(
    id integer NOT NULL,
    screen_name character varying COLLATE pg_catalog."default",
    default_profile character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    created_at date,
    geo_enabled integer,
    lang character varying COLLATE pg_catalog."default",
    statuses_count integer,
    followers_count integer,
    favourites_count integer,
    verified integer,
    account_type integer
);
END;